baseurl: "https://tools.kausalflow.com" # Controls base URL
languageCode: "en-US" # Controls html lang attribute
title: "Tools for Academic Research" # Homepage title and page title suffix
paginate: 12 # Number of posts to show before paginating
theme: "bulma" # to use as default theme

enableRobotsTXT: true # Suggested, it generates a robots.txt
googleAnalytics: "G-C1M9H41ZZ9" # Optional, add tracking Id for analytics
disqusShortname: "" # Optional, add Disqus shortname for comments
SectionPagesMenu: "main" # Enable menu system for lazy bloggers


menu:
  main:
    - name: "Tools"
      weight: 1
      identifier: tools
      url: /tools/
    # - name: "<i class=\"fab fa-searchengin\" style=\"margin-right: 0.3em;\"></i>Advanced Search"
    #   weight: 2
    #   identifier: search
    #   url: /search/
    - name: "<i class=\"fas fa-microchip\" style=\"margin-right: 0.3em;\"></i>AI Collection"
      weight: 2
      identifier: collection-ai
      url: /collections/ai
    - name: "<i class=\"fas fa-folder-plus\" style=\"margin-right: 0.3em;\"></i> Submit New Tools"
      weight: 3
      identifier: submit
      url: /submit/
    - name: "<i class=\"fas fa-satellite-dish\" style=\"margin-right: 0.3em;\"></i>Community"
      weight: 4
      identifier: community
      url: "https://github.com/kausalflow/tools/discussions"

params:
  theme_variant: "journal" # possible value for the theme_variant `cerulean,cosmo,cyborg,darkly,flatly,journal,litera,lumen,lux,materia,minty,pulse,sandstone,simplex,slate,solar,spacelab,superhero,united,yeti`
  description: "A Curated List of Research Tool"
  logo: "/assets/logo/kausalflow_bare.png"
  favicon: "/assets/logo/kausalflow_bare.png"
  powered_by: "love" # Optional, controls name display on footer
  hide_author: false # Optional, set true to hide author name on posts
  images: # Suggested, controls default OpenGraph images controls author name display on meta tag
  github: "kausalflow/tools" # Optional, to display link to github account in menu bar
  twitter: "" # Optional, to display link to twitter account in menu bar
  facebook: "Research-Tools-101254031583772"
  sunspot: "http://sunspot.kausalflow.com/"
  author: "KausalFlow"
  editURL: "https://github.com/kausalflow/tools/edit/master/content/"
  noindex_kinds:
    - "taxonomyTerm"
  algolia:
    vars:
      - "title"
      - "summary"
      - "date"
      - "publishdate"
      - "expirydate"
      - "permalink"
      - "images"
      - "author"
      - "fields"
      - "platforms"
      - "file"
    params:
      - "categories"
      - "tags"
    options:
      appId: "GHN6Q94HKJ"
      apiKey: "2e4aba48a2586d24b6f1e0fe801ac4c9"
      indexName: "tools-kausalflow"
      hitsPerPage: 12
      routing: true
  comments:
    giscus:
      repo: "kausalflow/tools"
      repo_id: "MDEwOlJlcG9zaXRvcnkyNTg1NjU2ODg="
      category: "Comments"
      category_id: "DIC_kwDOD2lmOM4B-h15"


outputFormats:
  Algolia:
    baseName: "algolia"
    isPlainText: true
    mediaType: "application/json"
    notAlternative: true
  Tools:
    baseName: "tools"
    isPlainText: true
    mediaType: "application/json"
    notAlternative: true

outputs:
  home:
    - "HTML"
    - "RSS"
    - "Algolia"
    - "Tools"

taxonomies:
    author: "author"
    category: "categories"
    tag: "tags"
    collection: "collections"
